<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="inertial_macros.xacro"/>
 
    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

   <material name="orange">
    <color rgba="1 0.3 0.1 1"/>
    </material>

   <material name="blue">
    <color rgba="0.2 0.2 1 1"/>
    </material>

   <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
      <!-- BASE LINK -->
   <link name="base_link">

   </link>

    <!-- CHASSIS LINK-->
   <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-0.1 0 0"/>
   </joint>
   
   <link name="chassis">
       <visual>
         <origin xyz="0.15  0  0.075" />
         <geometry>
            <box size="0.3 0.3 0.15"/>
         </geometry>
         <material name="white"/>
       </visual>

       <collision>
        <origin xyz="0.15  0  0.075" />
        <geometry>
           <box size="0.3 0.3 0.15"/>
        </geometry>
        <material name="white"/>
       </collision>

       <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
        <origin xyz="0.15 0 0.075" rpy="0.0 0.0 0.0"/>
       </xacro:inertial_box>

   </link>


   <!-- LEFT WHEEL LINK -->

   <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 0.175 0" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
   </joint>



   <link name="left_wheel">
    <visual>
        <geometry>
            <cylinder radius="0.05" length="0.04"/>
        </geometry>
        <material name="blue"/>
    </visual>   
    <collision>
        <geometry>
            <cylinder radius="0.05" length="0.04"/>
        </geometry>
        <material name="blue"/>
    </collision>

    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
  </link>

<!-- RIGHT WHEEL LINK -->

<joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -0.175 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1"/>
   </joint>



   <link name="right_wheel">
    <visual>
        <geometry>
            <cylinder radius="0.05" length="0.04"/>
        </geometry>
        <material name="blue"/>
    </visual>   
    <collision>
        <geometry>
            <cylinder radius="0.05" length="0.04"/>
        </geometry>
        <material name="blue"/>
    </collision>

    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>

  </link>


  <!-- CASTER WHEEL LINK -->

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="0.24 0 0"/>
  </joint>
  
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>  
      <material name="black"/>
    </visual>

    <collision>
            <geometry>
              <sphere radius="0.05"/>
            </geometry>  
            <material name="black"/> 
    </collision>

    <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
    
  </link>


   
</robot>